# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pulsage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for Pulsage

 
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  target 'PulsageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
